# Form implementation generated from reading ui file '/media/martokk/FILES/dev/frameworks/workflow_manager/assets/ui/pyqt5_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStatusTip("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QVBoxLayout()
        self.header.setSpacing(6)
        self.header.setObjectName("header")
        self.headerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.headerHorizontalLayout.setObjectName("headerHorizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.headerHorizontalLayout.addItem(spacerItem)
        self.headerIcon = QtWidgets.QLabel(self.centralwidget)
        self.headerIcon.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headerIcon.sizePolicy().hasHeightForWidth())
        self.headerIcon.setSizePolicy(sizePolicy)
        self.headerIcon.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.headerIcon.setScaledContents(True)
        self.headerIcon.setWordWrap(False)
        self.headerIcon.setObjectName("headerIcon")
        self.headerHorizontalLayout.addWidget(self.headerIcon)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.headerHorizontalLayout.addWidget(self.label)
        self.headerAppName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.headerAppName.setFont(font)
        self.headerAppName.setObjectName("headerAppName")
        self.headerHorizontalLayout.addWidget(self.headerAppName)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.headerHorizontalLayout.addItem(spacerItem1)
        self.header.addLayout(self.headerHorizontalLayout)
        self.verticalLayout_2.addLayout(self.header)
        self.horizontalLine = QtWidgets.QFrame(self.centralwidget)
        self.horizontalLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizontalLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizontalLine.setObjectName("horizontalLine")
        self.verticalLayout_2.addWidget(self.horizontalLine)
        self.script = QtWidgets.QWidget(self.centralwidget)
        self.script.setObjectName("script")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.script)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scriptAction = QtWidgets.QGroupBox(self.script)
        self.scriptAction.setObjectName("scriptAction")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scriptAction)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line1LineEdit = QtWidgets.QLineEdit(self.scriptAction)
        self.line1LineEdit.setObjectName("line1LineEdit")
        self.gridLayout.addWidget(self.line1LineEdit, 0, 2, 1, 1)
        self.line2BrowseButton = QtWidgets.QPushButton(self.scriptAction)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.line2BrowseButton.setIcon(icon)
        self.line2BrowseButton.setObjectName("line2BrowseButton")
        self.gridLayout.addWidget(self.line2BrowseButton, 1, 3, 1, 1)
        self.line2LineEdit = QtWidgets.QLineEdit(self.scriptAction)
        self.line2LineEdit.setObjectName("line2LineEdit")
        self.gridLayout.addWidget(self.line2LineEdit, 1, 2, 1, 1)
        self.runScriptButton = QtWidgets.QPushButton(self.scriptAction)
        icon = QtGui.QIcon.fromTheme("text-x-script")
        self.runScriptButton.setIcon(icon)
        self.runScriptButton.setObjectName("runScriptButton")
        self.gridLayout.addWidget(self.runScriptButton, 3, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.line1BrowseButton = QtWidgets.QPushButton(self.scriptAction)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.line1BrowseButton.setIcon(icon)
        self.line1BrowseButton.setObjectName("line1BrowseButton")
        self.gridLayout.addWidget(self.line1BrowseButton, 0, 3, 1, 1)
        self.line1Label = QtWidgets.QLabel(self.scriptAction)
        self.line1Label.setObjectName("line1Label")
        self.gridLayout.addWidget(self.line1Label, 0, 1, 1, 1)
        self.line2Label = QtWidgets.QLabel(self.scriptAction)
        self.line2Label.setObjectName("line2Label")
        self.gridLayout.addWidget(self.line2Label, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.scriptAction)
        self.scriptOutput = QtWidgets.QGroupBox(self.script)
        self.scriptOutput.setObjectName("scriptOutput")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scriptOutput)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.actionPlainTextEdit = QtWidgets.QPlainTextEdit(self.scriptOutput)
        self.actionPlainTextEdit.setObjectName("actionPlainTextEdit")
        self.verticalLayout_3.addWidget(self.actionPlainTextEdit)
        self.verticalLayout_4.addWidget(self.scriptOutput)
        self.verticalLayout_2.addWidget(self.script)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 19))
        self.menubar.setObjectName("menubar")
        self.menuScripts = QtWidgets.QMenu(self.menubar)
        self.menuScripts.setObjectName("menuScripts")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMain = QtWidgets.QAction(MainWindow)
        self.actionMain.setObjectName("actionMain")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCustom = QtWidgets.QAction(MainWindow)
        self.actionCustom.setObjectName("actionCustom")
        self.menuScripts.addAction(self.actionMain)
        self.menuScripts.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionCustom)
        self.menubar.addAction(self.menuScripts.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.headerIcon.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><img src=":/resources/icon" height="64" width="64" /></p></body></html>',
            )
        )
        self.headerAppName.setText(_translate("MainWindow", "xxxxxxxxxx"))
        self.scriptAction.setTitle(_translate("MainWindow", "Action 1: Run Report"))
        self.line2BrowseButton.setText(_translate("MainWindow", "Browse"))
        self.runScriptButton.setText(_translate("MainWindow", "Run Script"))
        self.line1BrowseButton.setText(_translate("MainWindow", "Browse"))
        self.line1Label.setText(_translate("MainWindow", "line1Label"))
        self.line2Label.setText(_translate("MainWindow", "line2Label"))
        self.scriptOutput.setTitle(_translate("MainWindow", "Script Output:"))
        self.menuScripts.setTitle(_translate("MainWindow", "Scripts"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionMain.setText(_translate("MainWindow", "Main"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionCustom.setText(_translate("MainWindow", "Get more custom scripts..."))


import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
